### ISSUE TITLE
Uncaught Invariant Violation: HighlightWords.render(): A valid React element (or null) must be returned.

### ISSUE THREAD

**Issue by PhilippMelnikov** [vitalybaev/react-dadata#26]
Здравствуйте коллеги. Ошибка с новой версией пакета 2.1.1 в приложении с react 15.6.2.
При заполнении инпута компонента AddressSuggestions
`react_devtools_backend.js:32 Uncaught Invariant Violation: HighlightWords.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.
    at invariant (http://localhost:3000/v24865/build/app.js:20790:15)
    at ReactCompositeComponentWrapper._renderValidatedComponent (http://localhost:3000/v24865/build/app.js:151436:111)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:3000/v24865/build/app.js:150967:30)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:3000/v24865/build/app.js:150863:21)
    at Object.mountComponent (http://localhost:3000/v24865/build/app.js:41525:35)
    at Object.mountComponent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:32:13702)
    at Object.e.<computed> [as mountComponent] (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:32:10511)
    at ReactDOMComponent.mountChildren (http://localhost:3000/v24865/build/app.js:150236:44)
    at ReactDOMComponent._createInitialChildren (http://localhost:3000/v24865/build/app.js:148424:32)
    at ReactDOMComponent.mountComponent (http://localhost:3000/v24865/build/app.js:148243:12)
    at Object.mountComponent (http://localhost:3000/v24865/build/app.js:41525:35)
    at Object.mountComponent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:32:13702)
    at Object.e.<computed> [as mountComponent] (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:32:10511)
    at ReactDOMComponent.mountChildren (http://localhost:3000/v24865/build/app.js:150236:44)
    at ReactDOMComponent._createInitialChildren (http://localhost:3000/v24865/build/app.js:148424:32)
    at ReactDOMComponent.mountComponent (http://localhost:3000/v24865/build/app.js:148243:12)
    at Object.mountComponent (http://localhost:3000/v24865/build/app.js:41525:35)
    at Object.mountComponent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:32:13702)
    at Object.e.<computed> [as mountComponent] (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:32:10511)
    at Object.updateChildren (http://localhost:3000/v24865/build/app.js:150570:51)
    at ReactDOMComponent._reconcilerUpdateChildren (http://localhost:3000/v24865/build/app.js:150206:32)
    at ReactDOMComponent._updateChildren (http://localhost:3000/v24865/build/app.js:150310:31)
    at ReactDOMComponent.updateChildren (http://localhost:3000/v24865/build/app.js:150297:12)
    at ReactDOMComponent._updateDOMChildren (http://localhost:3000/v24865/build/app.js:148667:12)
    at ReactDOMComponent.updateComponent (http://localhost:3000/v24865/build/app.js:148481:10)
    at ReactDOMComponent.receiveComponent (http://localhost:3000/v24865/build/app.js:148443:10)
    at Object.receiveComponent (http://localhost:3000/v24865/build/app.js:41604:22)
    at Object.receiveComponent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:32:14300)
    at Object.e.<computed> [as receiveComponent] (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:32:10511)
    at ReactCompositeComponentWrapper._updateRenderedComponent (http://localhost:3000/v24865/build/app.js:151359:23)
    at ReactCompositeComponentWrapper._performComponentUpdate (http://localhost:3000/v24865/build/app.js:151329:10)
    at ReactCompositeComponentWrapper.updateComponent (http://localhost:3000/v24865/build/app.js:151250:12)
    at ReactCompositeComponentWrapper.performUpdateIfNecessary (http://localhost:3000/v24865/build/app.js:151166:12)
    at Object.performUpdateIfNecessary (http://localhost:3000/v24865/build/app.js:41636:22)
    at Object.performUpdateIfNecessary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:32:13993)
    at Object.e.<computed> [as performUpdateIfNecessary] (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:32:10511)
    at runBatchedUpdates (http://localhost:3000/v24865/build/app.js:27781:21)
    at ReactReconcileTransaction.perform (http://localhost:3000/v24865/build/app.js:48592:20)
    at ReactUpdatesFlushTransaction.perform (http://localhost:3000/v24865/build/app.js:48592:20)
    at ReactUpdatesFlushTransaction.perform (http://localhost:3000/v24865/build/app.js:27720:32)
    at Object.flushBatchedUpdates (http://localhost:3000/v24865/build/app.js:27803:19)
    at ReactDefaultBatchingStrategyTransaction.closeAll (http://localhost:3000/v24865/build/app.js:48658:25)
    at ReactDefaultBatchingStrategyTransaction.perform (http://localhost:3000/v24865/build/app.js:48605:16)
    at Object.batchedUpdates (http://localhost:3000/v24865/build/app.js:152463:26)
    at Object.enqueueUpdate (http://localhost:3000/v24865/build/app.js:27831:22)
    at enqueueUpdate (http://localhost:3000/v24865/build/app.js:60734:16)
    at Object.enqueueSetState (http://localhost:3000/v24865/build/app.js:60928:5)
    at AddressSuggestions.ReactComponent.setState (http://localhost:3000/v24865/build/app.js:85712:16)
    at XMLHttpRequest._this.xhr.onreadystatechange (http://localhost:3000/v24865/build/app.js:108377:31)
`

**Comment by vitalybaev** [comment]
Спасибо за issue! Опубликовал фикс `2.1.2`
