### ISSUE TITLE
Does not work with react 16

### ISSUE THREAD

**Issue by pluhmylkin** [vitalybaev/react-dadata#4]
I can't run the plugin because it gives an error when I connect the library

```
For help see https://nodejs.org/en/docs/inspector
project/node_modules/react-dadata/dist/react-dadata.css:1
(function (exports, require, module, __filename, __dirname) { .react-dadata__container {
                                                              ^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/project/node_modules/react-dadata/dist/index.js:15:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)

```

**Comment by vitalybaev** [comment]
Sorry for the late answer. It seems that you loaded css file without property loader. So webpack doesn't understand css files out the box.

**Comment by qqalexqq** [comment]
The error happens because the .css is imported directly in the contents of the index.js file in dist/. What is the fix for the problem with webpack?
